# Aktifkan penggunaan AndroidX
android.useAndroidX=true

# Otomatis konversi library pihak ketiga yang masih memakai Support Library lama ke AndroidX
android.enableJetifier=true

# Pengaturan memori saat build (opsional, untuk mempercepat proses di GitHub Actions)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
