# Mengaktifkan dukungan AndroidX
android.useAndroidX=true

# Mengonversi library legacy/third-party ke AndroidX secara otomatis (opsional tapi disarankan)
android.enableJetifier=true

# Optimasi alokasi memori Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
